name: Source Lint Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linting Tools
        run: pip install black djlint

      - name: Run black (check only)
        run: black --check .

      - name: Run djlint (check only)
        run: djlint --check --quiet --profile=jinja . 
